# Generated by Django 4.0.6 on 2022-07-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('vendor', models.CharField(max_length=31)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('media', models.FileField(blank=True, upload_to='video/%Y/%m/%d/')),
                ('purpose_price', models.IntegerField()),
                ('sale_price', models.IntegerField(blank=True)),
                ('gain', models.IntegerField(blank=True)),
                ('duration_of_sale', models.TimeField(blank=True)),
                ('buyer', models.CharField(max_length=31)),
                ('seller', models.CharField(max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bought_at', models.DateTimeField(blank=True)),
                ('sale_at', models.DateTimeField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
    ]
